from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os


def generate_pdf(
    filename,
    student_name,
    roll_number,
    topic,
    transcript,
    similarity,
    level,
    duration,
    rms,
    fillers
):

    os.makedirs("reports_output", exist_ok=True)

    filepath = os.path.join("reports_output", filename)

    c = canvas.Canvas(filepath, pagesize=letter)

    width, height = letter

    y = height - 50

    # -----------------------------
    # Title
    # -----------------------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Voice-Based Concept Understanding Analyser")

    y -= 40

    c.setFont("Helvetica", 12)

    # -----------------------------
    # Student Details
    # -----------------------------
    c.drawString(50, y, f"Student Name : {student_name}")
    y -= 20

    c.drawString(50, y, f"Roll Number : {roll_number}")
    y -= 20

    c.drawString(50, y, f"Topic : {topic}")
    y -= 30

    # -----------------------------
    # Transcript
    # -----------------------------
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Transcript")
    y -= 20

    c.setFont("Helvetica", 11)

    text = c.beginText(50, y)
    text.textLines(transcript)
    c.drawText(text)

    y -= 120

    # -----------------------------
    # Analysis
    # -----------------------------
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "Analysis")
    y -= 25

    c.setFont("Helvetica", 11)

    c.drawString(50, y, f"Similarity Score : {similarity:.2f}%")
    y -= 20

    c.drawString(50, y, f"Understanding Level : {level}")
    y -= 20

    c.drawString(50, y, f"Duration : {duration} sec")
    y -= 20

    c.drawString(50, y, f"RMS Energy : {rms}")
    y -= 20

    c.drawString(50, y, f"Filler Words : {fillers}")

    y -= 40

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        50,
        y,
        "Generated by Voice-Based Concept Understanding Analyser"
    )

    c.save()

    return filepath